requires pip at compile time
+ /usr/bin/python3 setup.py build '--build-base=build-3'
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import pip
ModuleNotFoundError: No module named 'pip'